### ISSUE TITLE
Getting gem versioning problem

### ISSUE THREAD

**Issue by FayeFang** [contentful/contentful-database-importer.rb#16]
Everything was working perfectly a month ago and when I modified the script a bit and tried to run it again, I get the following error at line `require 'contentful/database_importer'`. Can you take a look at it please? Thanks!

I tried to update every possible contentful gem and still no result.
```
/usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'contentful-management' to activate (Gem::LoadError)
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/commands/create_space.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap/commands.rb:1:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful_bootstrap-3.6.1/lib/contentful/bootstrap.rb:4:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contentful-database-importer-0.3.2/lib/contentful/database_importer.rb:6:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /usr/local/var/rbenv/versions/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
```

**Comment by FayeFang** [comment]
Anyone updates on this?

**Comment by dlitvakb** [comment]
Hey @FayeFang,

Sorry not to answer previously, I was on vacation.

Have you ran `bundle install` on your directory? Looks like `contentful-management` is not installed.

Cheers

**Comment by FayeFang** [comment]
yeah I did...after uninstalling/re-installing gems, it works now. thanks for the help!
