### ISSUE TITLE
Updating an existing space instead of creating one from scratch

### ISSUE THREAD

**Issue by rngadam** [contentful/contentful-database-importer.rb#2]
I have a space that already exist.

I've configured config.space_name with the name of that existing space.

Instead of using that existing space, the tool creates a space with the same name and populates it.

Is there a way to use the existing space instead of creating a new one?

**Comment by rngadam** [comment]
If I replace:

````
      Contentful::Bootstrap::CommandRunner.new.create_space(
        config.space_name,
        json_template: file.path
      )
```

by 

```
      Contentful::Bootstrap::CommandRunner.new.update_space(
        config.space_name,
        json_template: file.path
      )
```

in contentful-database-importer.rb/lib/contentful/database_importer.rb

I get:

```
> bundle exec ruby import.rb
OAuth token found, moving on!
Updating Space 'Davis staging'
/Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful-management-0.9.0/lib/contentful/management/client.rb:119:in `execute_request': Service Unavailable, contenful.com API seems to be down (Contentful::Management::ServiceUnavailable)
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful-management-0.9.0/lib/contentful/management/client.rb:139:in `get'
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful-management-0.9.0/lib/contentful/management/request.rb:37:in `get'
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful-management-0.9.0/lib/contentful/management/space.rb:48:in `find'
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful_bootstrap-3.3.0/lib/contentful/bootstrap/commands/update_space.rb:39:in `fetch_space'
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful_bootstrap-3.3.0/lib/contentful/bootstrap/commands/update_space.rb:26:in `run'
	from /Users/rngadam/.rvm/gems/ruby-2.2.3/gems/contentful_bootstrap-3.3.0/lib/contentful/bootstrap/command_runner.rb:32:in `update_space'
	from /Users/rngadam/EIC/src/contentful-database-importer.rb/lib/contentful/database_importer.rb:45:in `run_bootstrap!'
	from /Users/rngadam/EIC/src/contentful-database-importer.rb/lib/contentful/database_importer.rb:57:in `run!'
	from import.rb:32:in `<main>'
```

**Comment by dlitvakb** [comment]
Hey @rngadam,

I will be adding the `update_space` option in the next release, but instead of sending it a space name, you need to provide `space_id`, should work after that.

I'm planning on adding DB Query support for people that want to specify datasets within each Content Type, instead of running everything for the whole tables along with this feature, it's a bit more work and that's why it wasn't implemented this time round.

Cheers

**Comment by dlitvakb** [comment]
Hey @rngadam,

Update Space is now included in the `master` branch, it's not yet released though, as I need to go through some more manual testing to ensure it's 100% working.

Hope that helps

**Comment by dlitvakb** [comment]
This has been now released

Cheers
