### ISSUE TITLE
Wordpress posts table gives InvalidValue error

### ISSUE THREAD

**Issue by rainmaker2k** [contentful/contentful-database-importer.rb#22]
I'm trying to use this script with a Wordpress database. I followed the README and created this simple import.rb file.
```ruby
require 'contentful/database_importer'

class WordPressPostsTable
  include Contentful::DatabaseImporter::Resource

  self.table_name = 'wp_posts'
  self.content_type_id = 'wordpress_posts'
  self.content_type_name = 'Wordpress Post' 

  id Contentful::DatabaseImporter::IdGenerator::Base, template: '{{content_type_id}}_{{title}}_{{index}}'

  field :post_title, maps_to: :title, type: :string
  field :post_content, maps_to: :content, type: :text
end

Contentful::DatabaseImporter.setup do |config|
  config.space_name = 'Blog'
  config.database_connection = 'mysql://wordpress:wordpress@db:3306/wordpress'
  config.locale = 'en-US'
end

Contentful::DatabaseImporter.run!
```

But when I try to run this with `bundle exec ruby import rb`, it returns with this stacktrace. 
```
/usr/local/lib/ruby/2.3.0/time.rb:302:in `local': ArgumentError: argument out of range (Sequel::InvalidValue)
    from /usr/local/lib/ruby/2.3.0/time.rb:302:in `make_time'
    from /usr/local/lib/ruby/2.3.0/time.rb:366:in `parse'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/core.rb:334:in `string_to_datetime'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/timezones.rb:136:in `convert_input_timestamp'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/timezones.rb:77:in `convert_timestamp'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/database/misc.rb:300:in `to_application_timestamp'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:387:in `call'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:387:in `block in yield_rows'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:387:in `each'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:387:in `yield_rows'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:333:in `block in fetch_rows'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:192:in `_execute'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `block in execute'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `block in synchronize'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/connection_pool/threaded.rb:107:in `hold'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/database/connecting.rb:301:in `synchronize'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/utils/mysql_mysql2.rb:37:in `execute'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:1135:in `execute'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:374:in `execute'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/adapters/mysql.rb:318:in `fetch_rows'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:155:in `each'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:52:in `block in all'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:1052:in `_all'
    from /usr/local/bundle/gems/sequel-4.49.0/lib/sequel/dataset/actions.rb:52:in `all'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/resource_class_methods.rb:74:in `all'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/json_generator.rb:43:in `create_entries'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/json_generator.rb:14:in `block in generate_json'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/json_generator.rb:11:in `each'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/json_generator.rb:11:in `generate_json'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer/json_generator.rb:78:in `generate_json!'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer.rb:37:in `generate_json!'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer.rb:42:in `generate_json_file!'
    from /usr/local/bundle/gems/contentful-database-importer-0.6.0/lib/contentful/database_importer.rb:71:in `run!'
    from import.rb:28:in `<main>'
```
Any idea what this could be?

**Comment by dlitvakb** [comment]
Hey @rainmaker2k,

I'm not entirely sure what may be going on without more context, apparently, the SQL Driver is failing to fetch a date from your wordpress table, but I can't for sure confirm this without knowing the structure of your database.

Cheers
