### ISSUE TITLE
Importing assest fails during creation

### ISSUE THREAD

**Issue by eric-gymondo** [contentful/contentful-database-importer.rb#25]
I'm trying to import a simple entity with an asset related to it but during the import I get, I already tried many things like clean up the whole workspace

```
Uncaught exception: can't modify frozen String: ""
	/usr/local/lib/ruby/gems/2.7.0/gems/http-2.2.2/lib/http/response/body.rb:57:in `force_encoding'
	/usr/local/lib/ruby/gems/2.7.0/gems/http-2.2.2/lib/http/response/body.rb:57:in `to_s'
	/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/forwardable.rb:235:in `to_s'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/response.rb:85:in `no_content_response?'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/response.rb:33:in `initialize'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:387:in `new'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:387:in `execute_request'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:459:in `put'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/request.rb:51:in `put'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:61:in `block in process_file'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:53:in `each'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:53:in `process_file'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:129:in `rescue in block in create_assets'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:112:in `block in create_assets'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `each'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `create_assets'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:20:in `run'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:54:in `update_json_template'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:32:in `run'
	/usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/command_runner.rb:23:in `update_space'
	/Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:60:in `bootstrap_update_space!'
	/Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:80:in `update_space!'
	/Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/import.rb:354:in `<top (required)>'

```
the import.rb looks like this

```class Program
  include Contentful::DatabaseImporter::Resource

  self.table_name = 'program'
  self.content_type_id = 'program'
  self.content_type_name = 'program'

  id Contentful::DatabaseImporter::IdGenerator::Base, template: '{{content_type_id}}_{{id}}' # Optional - By default it's the IdGenerator::Base(template: '{{content_type_id}}_{{index}}')

  field :id, type: :integer
  field :femaleWebTitle, type: :asset

end```

**Comment by eric-gymondo** [comment]
Just an extra info when I try to run again
```

Updating from JSON Template '/Users/eric.santos/Github/contentful-database-importer.rb/import_Gymondo Contentful Space20200611-15568-887wbd'
Creating Asset 'webapp-titleimage-wide'
Asset 'webapp_titleimage_wide' already created! Updating instead.
Traceback (most recent call last):
	15: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/import-program.rb:36:in `<main>'
	14: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:80:in `update_space!'
	13: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:60:in `bootstrap_update_space!'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/command_runner.rb:23:in `update_space'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:32:in `run'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:54:in `update_json_template'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:20:in `run'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `create_assets'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `each'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:114:in `block in create_assets'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/environment_association_methods_factory.rb:23:in `create'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/resource.rb:256:in `create'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/resource_requester.rb:31:in `create'
	 2: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/request.rb:51:in `put'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:459:in `put'
/usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:388:in `execute_request': HTTP status code: 409 Conflict (Contentful::Management::Conflict)
Message: Version mismatch error. The version you specified was incorrect. This may be due to someone else editing the content.
Request ID: 2f08a9eb2ea57b0e240255d8209b01be
	22: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/import-program.rb:36:in `<main>'
	21: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:80:in `update_space!'
	20: from /Users/eric.santos/Github/contentful-database-importer.rb/lib/contentful/database_importer.rb:60:in `bootstrap_update_space!'
	19: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/command_runner.rb:23:in `update_space'
	18: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:32:in `run'
	17: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/commands/update_space.rb:54:in `update_json_template'
	16: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:20:in `run'
	15: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `create_assets'
	14: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:111:in `each'
	13: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:112:in `block in create_assets'
	12: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful_bootstrap-3.12.0/lib/contentful/bootstrap/templates/base.rb:129:in `rescue in block in create_assets'
	11: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:53:in `process_file'
	10: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:53:in `each'
	 9: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/asset.rb:61:in `block in process_file'
	 8: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/request.rb:51:in `put'
	 7: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:459:in `put'
	 6: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:387:in `execute_request'
	 5: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/client.rb:387:in `new'
	 4: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/response.rb:33:in `initialize'
	 3: from /usr/local/lib/ruby/gems/2.7.0/gems/contentful-management-2.12.0/lib/contentful/management/response.rb:85:in `no_content_response?'
	 2: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/forwardable.rb:235:in `to_s'
	 1: from /usr/local/lib/ruby/gems/2.7.0/gems/http-2.2.2/lib/http/response/body.rb:57:in `to_s'
/usr/local/lib/ruby/gems/2.7.0/gems/http-2.2.2/lib/http/response/body.rb:57:in `force_encoding': can't modify frozen String: "" (FrozenError)
```

**Comment by eric-gymondo** [comment]
Turns out was an issue with the ruby version that I was running 2.7.0 and seems like something related to immutable strings was introduced, I'm not sure actually maybe the repo owner can answer what's the compatibility.
