### ISSUE TITLE
undefined method query=

### ISSUE THREAD

**Issue by madalinoprea** [contentful/contentful-database-importer.rb#4]
I'm getting this error when I'm running `bundle exec ruby import.rb`:

```bash
import.rb:7:in `<class:Course>': undefined method `query=' for Course:Class (NoMethodError)
	from import.rb:5:in `<main>'
```

My `import.rb` file looks like this:

```
require 'contentful/database_importer'

# Table definitions
class Course
  include Contentful::DatabaseImporter::Resource
  self.query = "client_id = 0 AND parent_id = 0"

  self.table_name = 'courses'
  self.content_type_id = 'course'
  self.content_type_name = 'Course'

  id Contentful::DatabaseImporter::IdGenerator::ContentfulLike, template: '{{content_type_id}}_{{id}}'
  field :id, type: :number, exclude_from_output: true
  field :title, type: :string
  field :description, type: :text
  field :status, type: :number
end

Contentful::DatabaseImporter.setup do |config|
  config.space_name = 'Sandbox #1'
  # config.space_id = 'xyx'
  config.database_connection = 'mysql2://root:@127.0.0.1:3306/hp2?encoding=utf8'
end

json = Contentful::DatabaseImporter.generate_json!
File.open('content_types.json', 'w') { |file| file.write(json) }
```

My best guess is that version for `contentful-database-importer` loaded from rubygems is not the latest one.

**Comment by dlitvakb** [comment]
Hey @madalinoprea,

The `::query=` method is only present on the `master` branch, please make sure that's what you're using and not the `0.1.0` release.

You can change that by changing the line in your `Gemfile` to:

`gem 'contentful-database-importer', github: 'contentful/contentful-database-importer.rb', branch: 'master'`

Hope that helps

**Comment by madalinoprea** [comment]
Thanks @dlitvakb . 

This worked for me.
